version: '3.8'

services:
  easybooking_db:
    image: postgres
    container_name: easybooking_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: easybooking
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
